### PR TITLE
Refine UI Implementation & Refine DB Revamped

### PR DESCRIPTION
**Pull request by cydh**
* Released of the refine UI by @Lemongrass3110 on https://github.com/rathena/rathena/pull/2494
* Added 'Blacksmith blessing' system in refine npcs by @Atemo on https://github.com/rathena/rathena/pull/2494
* Revamped Refine DB

### CODE REVIEW

**Comment by ghost** [comment]
@cydh how do I pull this to master? Would like to try this PR

**Comment by cydh** [comment]
u can add new remote for my this repo, fetch it, merge to master or just apply the https://github.com/cydh/rathena/pull/9.diff

**Comment by ghost** [comment]
@cydh How do I download the patch?

**Comment by cydh** [comment]
just CTRL+S the .diff page file

**Comment by ghost** [comment]
@cydh is this not possible via pull? its much easier there so I can always update if you have update too.

**Comment by cydh** [comment]
> u can add new remote for my this repo, fetch it, merge to master

add a new remote, fetch the branch, checkout it (I'm not teaching basic git usage, sorry)

**Comment by ghost** [comment]
Wooow thanks @cydh <3

**Comment by admkakaroto** [comment]
after applying this, whenever I put any equipment to head the game crash the client.
  
#edit:
I'm an idiot, I took it easy and it worked 100%, sorry.

**Comment by cydh** [comment]
@admkakaroto it's must because you applied it wrong

**Comment by admkakaroto** [comment]
@cydh Can I use this PR? I saw the PR of Lemon, but do not have the blacksmith blessing, could you use this one here?

**Comment by admkakaroto** [comment]
By using the 'feature.refineui: 2' option I am getting this message:

Msg: [Warning]: conf/battle/feature.conf refine UI is enabled in scripts but disabled in general, enabling...

**Comment by admkakaroto** [comment]
@cydh there is a terrible bug in this patch if you equip the item after it is in the refine interface and if it fails you do not lose the item and the refinement does not add up as well.

**Comment by luan122** [comment]
hello @cydh , could you update this PR to the lastest version of rA?

**Comment by ghost** [comment]
Can you update this @cydh ? thanks!

**Comment by cydh** [comment]
just updated this PR

**Comment by teededung** [comment]
Please update Holink and Wagjak from https://github.com/rathena/rathena/commit/a12c79f7828031b0e521ebf69afac47c347345e3

**Comment by mjonrest** [comment]
i saw new 'master' not match to this change... is there any update soon??

thanks

**Comment by cydh** [comment]
I'll update/rebase this messed up branch this weekend

**Comment by mjonrest** [comment]
thanks for your good work

**Comment by cydh** [comment]
Thank you for using this PR, I will close this since the commits are in a mess and move to cydh#10
There are no changes, except `getblacksmithblessing` (I added it while forgot that already add `REFINE_BS_BLESSING` type for `getequippercentrefinery`)

**Pull request closed without merging**
